In [2]:
import torch
import pandas as pd

In [2]:
#extract korean dataset
from load_korean_data import extract_zips

extract_zips()

Done extracting Korean data

In [2]:

df_madalena_comfort = pd.read_csv('datasets/madalena_comfort.csv')

df_madalena_comfort.head(50)

,date,Room,CO2[ppm],PM4[ug/m3],Lighting[lux],T_in[°C],RH [%],PM10[ug/m3],PM2_5[ug/m3],PM1[ug/m3],PM0_5[ug/m3],T_out [°C]
0,2024-07-01 00:00:00,E145,624.23,65.43,0.00,28.46,55.51,65.44,65.42,65.22,56.81,24.5
1,2024-07-01 01:00:00,E145,629.00,66.77,0.00,28.48,56.39,66.78,66.76,66.56,57.97,24.0
2,2024-07-01 02:00:00,E145,640.13,67.78,0.00,28.45,56.74,67.79,67.77,67.57,58.85,22.3
3,2024-07-01 03:00:00,E145,639.77,68.00,0.00,28.39,57.08,68.01,67.98,67.78,59.04,22.0
4,2024-07-01 04:00:00,E145,643.31,67.25,0.03,28.35,57.57,67.26,67.24,67.04,58.39,21.5
5,2024-07-01 05:00:00,E145,619.97,68.98,3.82,28.41,57.81,68.99,68.96,68.76,59.89,21.3
6,2024-07-01 06:00:00,E145,565.29,74.80,35.68,28.62,57.59,74.81,74.79,74.57,64.95,22.0
7,2024-07-01 07:00:00,E145,525.40,69.85,32.15,28.70,57.31,69.86,69.84,69.63,60.65,22.5
8,2024-07-01 08:00:00,E145,494.33,67.51,5.58,28.79,56.73,67.53,67.50,67.30,58.62,23.3
9,2024-07-01 09:00:00,E145,486.38,82.80,3.48,28.80,56.46,82.81,82.78,82.54,71.89,25.5
10,2024-07-01 10:00:00,E145,522.12,80.46,2.02,28.86,55.19,80.47,80.44,80.20,69.86,26.0
11,2024-07-01 11:00:00,E145,562.83,74.24,1.35,28.83,52.51,74.25,74.22,74.00,64.46,27.1
12,2024-07-01 12:00:00,E145,581.19,60.72,0.66,28.80,52.34,60.73,60.71,60.53,52.72,28.5
13,2024-07-01 13:00:00,E145,577.92,41.08,6.23,28.88,52.98,41.08,41.07,40.95,35.66,29.5
14,2024-07-01 14:00:00,E145,481.15,33.04,38.90,29.01,54.02,33.05,33.04,32.94,28.69,29.8
15,2024-07-01 15:00:00,E145,476.15,13.17,33.96,28.94,51.61,13.18,13.17,13.13,11.44,27.0
16,2024-07-01 16:00:00,E145,493.86,9.66,0.00,28.87,51.82,9.67,9.66,9.63,8.39,25.5
17,2024-07-01 17:00:00,E145,516.26,8.89,0.00,28.77,52.08,8.89,8.89,8.84,7.67,24.5
18,2024-07-01 18:00:00,E145,547.77,8.14,0.00,28.65,52.42,8.14,8.13,8.05,6.94,20.0
19,2024-07-01 19:00:00,E145,599.47,7.74,0.00,28.58,52.86,7.75,7.73,7.67,6.63,18.5
20,2024-07-01 20:00:00,E145,647.84,7.98,0.00,28.49,53.58,7.98,7.97,7.94,6.89,18.1
21,2024-07-01 21:00:00,E145,723.05,9.07,0.00,28.48,54.17,9.07,9.07,9.04,7.87,18.0
22,2024-07-01 22:00:00,E145,752.71,10.00,0.00,28.51,54.84,10.00,10.00,9.97,8.68,18.0
23,2024-07-01 23:00:00,E145,758.72,8.86,0.00,28.43,55.02,8.86,8.86,8.83,7.69,17.9
24,2024-07-02 00:00:00,E145,757.73,8.29,0.00,28.37,55.07,8.29,8.29,8.26,7.20,18.0
25,2024-07-02 01:00:00,E145,752.98,7.83,0.00,28.33,55.00,7.83,7.83,7.81,6.80,18.0
26,2024-07-02 02:00:00,E145,756.88,8.23,0.00,28.15,54.93,8.23,8.23,8.21,7.15,17.5
27,2024-07-02 03:00:00,E145,709.42,9.31,0.00,28.02,54.71,9.31,9.31,9.28,8.08,17.0
28,2024-07-02 04:00:00,E145,554.65,12.84,5.19,27.88,53.18,12.85,12.84,12.80,11.15,17.0
29,2024-07-02 05:00:00,E145,530.76,13.66,27.33,27.71,52.54,13.66,13.66,13.62,11.86,16.2
30,2024-07-02 06:00:00,E145,466.71,9.89,1.42,27.44,51.66,9.89,9.89,9.86,8.59,17.0
31,2024-07-02 07:00:00,E145,456.18,9.92,40.98,27.22,52.72,9.92,9.91,9.88,8.61,18.5
32,2024-07-02 08:00:00,E145,489.93,10.04,7.86,27.17,53.27,10.05,10.04,9.99,8.68,21.0
33,2024-07-02 09:00:00,E145,443.06,8.39,2.57,27.16,50.60,8.39,8.38,8.36,7.28,23.5
34,2024-07-02 10:00:00,E145,451.25,6.78,0.00,27.07,47.14,6.78,6.78,6.76,5.88,24.0
35,2024-07-02 11:00:00,E145,456.42,9.22,0.38,26.87,44.65,9.22,9.22,9.19,8.01,25.3
36,2024-07-02 12:00:00,E145,463.54,8.84,1.99,26.77,44.10,8.84,8.84,8.81,7.67,26.5
37,2024-07-02 13:00:00,E145,479.16,9.24,8.81,26.73,45.13,9.24,9.24,9.21,8.02,27.0
38,2024-07-02 14:00:00,E145,643.27,11.42,39.97,27.05,47.62,11.42,11.42,11.39,9.92,26.8
39,2024-07-02 15:00:00,E145,528.15,9.35,9.11,27.21,46.79,9.36,9.35,9.30,8.07,27.0
40,2024-07-02 16:00:00,E145,432.52,7.85,0.31,27.26,45.25,7.86,7.85,7.83,6.82,26.5
41,2024-07-02 17:00:00,E145,451.03,9.94,0.00,27.33,45.32,9.94,9.94,9.91,8.63,25.7
42,2024-07-02 18:00:00,E145,506.81,9.43,1.14,27.38,45.77,9.43,9.43,9.40,8.19,26.0
43,2024-07-02 19:00:00,E145,457.61,16.37,0.00,27.50,45.31,16.38,16.37,16.32,14.22,25.5
44,2024-07-02 20:00:00,E145,447.99,15.46,0.43,27.51,45.64,15.46,15.46,15.41,13.42,24.9
45,2024-07-02 21:00:00,E145,548.63,13.48,0.00,27.51,47.07,13.48,13.47,13.43,11.70,24.0
46,2024-07-02 22:00:00,E145,553.73,12.89,0.00,27.75,48.71,12.89,12.88,12.85,11.19,23.0
47,2024-07-02 23:00:00,E145,493.88,9.42,0.00,27.91,49.45,9.42,9.42,9.39,8.18,22.9
48,2024-07-03 00:00:00,E145,473.39,11.86,0.00,27.96,49.49,11.87,11.86,11.83,10.30,20.0
49,2024-07-03 01:00:00,E145,457.60,15.55,0.00,27.84,49.18,15.55,15.55,15.50,13.50,19.5

In [ ]:
from glob import glob
import os
import gc


def optimize_memory(df):
    for col in df.select_dtypes(include=["int64", "float64"]).columns:
        df[col] = pd.to_numeric(df[col], downcast="integer")  
        df[col] = pd.to_numeric(df[col], downcast="float")   
    return df

In [20]:
def process_parquet(file):
    df = pd.read_parquet(file, engine="pyarrow")
    df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")  
    df = df.set_index("timestamp").sort_index()
    df = df[~df.index.duplicated(keep="first")]
    time_diffs = df.index.to_series().diff().dropna()
    detected_freq = time_diffs.mode()[0]  
    detected_freq_str = f"{int(detected_freq.total_seconds() * 1000)}ms"
    df = df.asfreq(detected_freq_str)
    df = df.interpolate(method="time")
    df_resampled = df.resample("1min").mean()
    return df_resampled

save_dir = "datasets/korean_processed"
def merge_daily_files(folder_path):
    files = [f for f in os.listdir(folder_path) if f.endswith(".parquet.gzip")]

    dfs = {}  

    for file in files:
        file_path = os.path.join(folder_path, file)
        df = process_parquet(file_path) 
        device_name = file.split("_", 1)[1].split(".parquet")[0]
        df = df.rename(columns={
            "active_power": f"{device_name}_active_power",
            "reactive_power": f"{device_name}_reactive_power"
        })
        dfs[device_name] = df  

    merged_df = list(dfs.values())[0]  

    for df in list(dfs.values())[1:]:
        merged_df = merged_df.merge(df, left_index=True, right_index=True, how="outer")

    del dfs
    gc.collect()
    return merged_df

def create_korean_files(path = "datasets/korean_extracted"):
    for folder in os.listdir(path):
        full_path = os.path.join(path, folder)
        for subfolder in os.listdir(full_path):
            full_subpath = os.path.join(full_path, subfolder)
            house_dfs = []
            for day_folder in os.listdir(full_subpath):
                day_path = os.path.join(full_subpath, day_folder)
                merged_df = merge_daily_files(day_path)
                merged_df = merged_df.fillna(0)
                print(f"Finished Day {day_path}")
                house_dfs.append(merged_df)
                del merged_df
                gc.collect()
            house_final_df = pd.concat(house_dfs)
            if house_final_df.index.name == "timestamp":
                house_final_df = house_final_df.reset_index()
            house_final_df = house_final_df.sort_values(by='timestamp').set_index('timestamp')
            house_final_df = house_final_df.fillna(0)

            house_final_df.to_csv(f"{save_dir}/{folder}.csv")
            del house_final_df
            del house_dfs
            gc.collect()
        
# merged_df = merge_daily_files(full_timestamp_path)
# merged_df = merged_df.fillna(0)
# merged_df.to_csv("datasets/korean_processed/merged_daily_data.csv")
create_korean_files()

Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161101
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161102
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161103
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161104
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161105
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161106
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161107
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161109
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161110
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161111
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161112
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161113
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161114
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161115
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161116
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161117
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161118
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161119
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161121
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161122
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161123
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161125
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161126
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161128
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161129
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161130
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161201
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161202
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161203
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161204
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161205
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161206
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161207
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161208
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161209
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161210
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161211
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161212
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161213
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161214
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161215
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161216
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161217
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161218
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161219
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161220
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161221
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161222
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161223
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161224
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161225
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161226
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161227
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161228
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161229
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20161230
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170101
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170102
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170103
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170104
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170105
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170106
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170107
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170108
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170109
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170110
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170111
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170112
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170113
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170114
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170115
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170116
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170117
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170118
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170119
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170120
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170121
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170122
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170123
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170124
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170125
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170126
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170127
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170128
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170129
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170130
Finished Day datasets/korean_extracted\enertalk-dataset-00\00\20170131
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161001
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161002
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161003
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161004
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161005
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161006
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161007
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161008
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161009
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161010
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161011
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161012
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161013
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161014
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161015
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161016
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161017
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161018
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161019
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161020
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161021
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161022
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161023
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161024
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161025
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161026
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161027
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161028
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161029
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161030
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161031
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161101
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161102
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161103
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161104
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161105
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161106
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161107
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161109
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161110
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161111
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161112
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161113
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161114
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161115
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161116
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161118
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161119
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161120
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161121
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161122
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161124
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161125
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161126
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161128
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161129
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161130
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161201
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161202
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161203
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161204
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161205
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161206
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161207
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161208
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161209
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161210
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161211
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161212
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161213
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161214
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161215
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161216
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161217
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161218
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161219
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161220
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161221
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161222
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161223
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161224
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161225
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161226
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161227
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161228
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161229
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20161230
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170101
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170102
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170103
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170104
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170105
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170106
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170107
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170108
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170109
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170110
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170111
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170112
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170113
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170114
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170115
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170116
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170117
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170118
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170119
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170120
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170121
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170122
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170123
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170124
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170125
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170126
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170127
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170128
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170129
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170130
Finished Day datasets/korean_extracted\enertalk-dataset-01\01\20170131
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161001
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161002
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161003
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161004
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161005
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161006
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161007
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161008
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161009
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161010
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161011
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161012
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161013
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161014
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161015
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161016
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161017
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161018
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161019
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161020
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161021
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161022
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161023
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161024
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161025
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161026
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161027
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161028
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161029
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161030
Finished Day datasets/korean_extracted\enertalk-dataset-02\02\20161031
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161001
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161002
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161003
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161004
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161005
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161006
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161007
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161008
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161009
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161010
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161011
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161012
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161013
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161014
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161015
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161016
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161018
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161019
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161020
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161021
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161022
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161023
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161024
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161025
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161026
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161027
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161028
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161029
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161030
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161031
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161102
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161103
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161104
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161105
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161106
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161107
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161109
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161110
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161112
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161114
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161115
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161116
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161117
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161118
Finished Day datasets/korean_extracted\enertalk-dataset-03\03\20161119

In [15]:
test_df = pd.read_csv("datasets/korean_processed/enertalk-dataset-00.csv")
test_df.head(100)

,Unnamed: 0,total_active_power,total_reactive_power,washing-machine_active_power,washing-machine_reactive_power,rice-cooker_active_power,rice-cooker_reactive_power,water-purifier_active_power,water-purifier_reactive_power,microwave_active_power,microwave_reactive_power,kimchi-fridge_active_power,kimchi-fridge_reactive_power,TV_active_power,TV_reactive_power,fridge_active_power,fridge_reactive_power
0,0,226.278702,-41.480791,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
1,1,426.839889,-85.463171,0.117980,6.110303,0.000000,0.000000,340.030000,-1.647143,0.475614,-1.545066,0.453393,-3.483571,0.0,0.0,0.0,0.0
2,2,417.073146,-142.700712,0.055135,5.976013,0.253236,0.018027,338.550340,-1.636741,0.496926,-1.530755,0.555059,-3.496886,0.0,0.0,0.0,0.0
3,3,147.948077,-145.353986,0.034107,6.011007,0.218430,0.029089,68.882708,-0.310016,0.512941,-1.562262,0.522887,-3.555151,0.0,0.0,0.0,0.0
4,4,68.593354,-145.734066,0.045174,6.006146,0.264247,0.036712,2.012237,0.099879,0.517540,-1.613452,0.534455,-3.589693,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,457.138866,37.400560,0.058651,6.034107,0.264835,-0.032953,82.064903,125.532717,0.474243,-1.600713,41.366940,12.010049,0.0,0.0,0.0,0.0
96,96,544.349344,65.819171,0.059654,6.056362,0.256974,0.017741,82.153492,125.067311,0.448399,-1.596424,121.983761,44.239222,0.0,0.0,0.0,0.0
97,97,359.020380,-18.701824,0.035061,6.067278,0.221695,0.037221,82.415382,125.786168,0.465852,-1.595567,4.431771,-1.982366,0.0,0.0,0.0,0.0
98,98,311.147881,-45.754289,0.039790,6.053757,0.258169,0.010144,82.371102,125.518387,0.501049,-1.609049,0.537575,-3.569677,0.0,0.0,0.0,0.0
99,99,318.128213,-46.506504,0.062073,6.061737,0.252187,0.009011,82.820967,125.938336,0.482936,-1.607833,0.526442,-3.630055,0.0,0.0,0.0,0.0